spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

camunda:
  bpm:
    admin-user:
      password: ${CAMUNDA_ADMIN_PASSWORD:demo}